/**:
  ros__parameters:
    debug: 0
    device: /dev/ttyACM0
    frame_id: gps_link
    uart1:
      baudrate: 9600
    tmode3: 0
    inf:
      all: true
    publish:
      all: true
      aid:
        hui: false
      nav:
        posecef: false
